// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-4JwptqQeiGBIXk1vA8SoqxI2K-j4aI',
    appId: '1:720763185617:web:0ecc19a702074cbcc8d8f0',
    messagingSenderId: '720763185617',
    projectId: 'goldmart-d100b',
    authDomain: 'goldmart-d100b.firebaseapp.com',
    databaseURL: 'https://goldmart-d100b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'goldmart-d100b.appspot.com',
    measurementId: 'G-2Y0GK4CGW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANgEsQdleSH3MLhiyA5YRB2cVd5qCaVns',
    appId: '1:720763185617:android:6284843f308e62efc8d8f0',
    messagingSenderId: '720763185617',
    projectId: 'goldmart-d100b',
    databaseURL: 'https://goldmart-d100b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'goldmart-d100b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA45kt_X4x6OIQmUpEFdQv77QMRq-GEP_U',
    appId: '1:720763185617:ios:50d331dfdf268c19c8d8f0',
    messagingSenderId: '720763185617',
    projectId: 'goldmart-d100b',
    databaseURL: 'https://goldmart-d100b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'goldmart-d100b.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA45kt_X4x6OIQmUpEFdQv77QMRq-GEP_U',
    appId: '1:720763185617:ios:50d331dfdf268c19c8d8f0',
    messagingSenderId: '720763185617',
    projectId: 'goldmart-d100b',
    databaseURL: 'https://goldmart-d100b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'goldmart-d100b.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh-4JwptqQeiGBIXk1vA8SoqxI2K-j4aI',
    appId: '1:720763185617:web:a418fb28f9a76987c8d8f0',
    messagingSenderId: '720763185617',
    projectId: 'goldmart-d100b',
    authDomain: 'goldmart-d100b.firebaseapp.com',
    databaseURL: 'https://goldmart-d100b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'goldmart-d100b.appspot.com',
    measurementId: 'G-X14VGRPFJ0',
  );
}
